#ifndef OPENBLAS_CONFIG_H
#define OPENBLAS_CONFIG_H
#define OPENBLAS_OS_@HOST_OS@	1
#define OPENBLAS_ARCH_@UC_ARCH@	1
#define OPENBLAS_C_@COMPILER_ID@	1
#define OPENBLAS___@BINARY@BIT__	1
#define OPENBLAS_FUNDERSCORE	@FU@
#cmakedefine OPENBLAS_BUNDERSCORE _
#cmakedefine OPENBLAS_NEEDBUNDERSCORE @OPENBLAS_NEEDBUNDERSCORE@
#cmakedefine01 OPENBLAS_NEED2UNDERSCORES

#cmakedefine OPENBLAS_QUAD_PRECISION
#cmakedefine OPENBLAS_EXPRECISION

